services:
    db-oracle:
        build: .
        container_name: ${CONTAINER_NAME}
        image: prosuite-db-oracle-193
        ports:
            - "1521:1521"
            - "5500:5500"
        env_file:
            - .env
        environment:
            - ORACLE_SID=${TNS_NAME}
            - ORACLE_HOME=/opt/oracle/product/19c/dbhome_1

        volumes:
            -  ${EXCHANGE_DIR}:/opt/oracle/exchange
            -  ${ORADATA_DIR}:/opt/oracle/oradata
            - ./sql:/sql
            - ./sh:/sh

        restart: unless-stopped

        deploy:
            resources:
                limits:
                    cpus: "4.0"
                    memory: 4G
